version: "3.4"
services:

 database:
  image: postgres:12-alpine
  container_name: database
  environment:
   - POSTGRES_USER=admin
   - POSTGRES_PASSWORD=admin
   - POSTGRES_DB=chatbot
  volumes:
   - ./database/database:/var/lib/postgresql/data
   - ./database/initdb.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
   - 5440:5432
  restart: unless-stopped