version: '3.4'
services:


  chatbot:
    image: chatbot:1.0
    build: 
      context: ./chatbot
      no_cache: true
      args:
        VECTOR_DATABASE_PORT: 8080
        LLM: meta-llama/Llama-3-8b-chat-hf
        LLM_API_KEY: '***************************'
        LLM_TEMPERATURE: 0.5
    container_name: chatbot
    ports:
      - 8001:8001
    volumes:
      - ./chatbot:/chatbot
    restart: unless-stopped
    depends_on:
      - vector_database
    networks:
      - net


  backend:
    image: backend:1.0
    build: 
      context: ./backend
      no_cache: true
      args:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: admin
        POSTGRES_DB: chatbot
        POSTGRES_PORT: 5432
        CHATBOT_PORT: 8001
        IS_RAG_USED: true
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    restart: unless-stopped
    depends_on:
      - chatbot
      - database
    networks:
      - net


  frontend:
    image: frontend:1.0
    build: 
      context: ./frontend
      no_cache: true
      args:
        BACKEND_PORT: 8000
        DEFAULT_LANGUAGE: en
    container_name: frontend
    ports:
      - 8501:8501
    volumes:
      - ./frontend:/frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - net

   
  database:
    image: postgres:12-alpine
    container_name: database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chatbot
    volumes:
      - ./database/database:/var/lib/postgresql/data
      - ./database/initdb.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - net

   
  vector_database:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.1
    container_name: vector_database
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./vector_database:/var/lib/weaviate
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      ENABLE_MODULES: 'text2vec-cohere,text2vec-huggingface,text2vec-palm,text2vec-openai,generative-openai,generative-cohere,generative-palm,ref2vec-centroid,reranker-cohere,qna-openai'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - net


networks:
  net:
    name: net
